// <auto-generated />
using System;
using CivicFlow.Modules.AdministrativeUnits.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CivicFlow.Modules.AdministrativeUnits.Persistence.Migrations
{
    [DbContext(typeof(AdmDbContext))]
    partial class AdmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("adm")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CivicFlow.Modules.AdministrativeUnits.Entities.AdministrativeBoundary", b =>
                {
                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<decimal?>("AreaKm2")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("area_km2");

                    b.Property<Polygon>("Bbox")
                        .IsRequired()
                        .HasColumnType("geometry(Polygon,4326)")
                        .HasColumnName("bbox");

                    b.Property<MultiPolygon>("Boundary")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon,4326)")
                        .HasColumnName("boundary");

                    b.Property<MultiPolygon>("BoundaryLod1")
                        .HasColumnType("geometry(MultiPolygon,4326)")
                        .HasColumnName("boundary_lod1");

                    b.Property<MultiPolygon>("BoundaryLod2")
                        .HasColumnType("geometry(MultiPolygon,4326)")
                        .HasColumnName("boundary_lod2");

                    b.Property<Point>("Centroid")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("centroid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("data_source");

                    b.Property<Point>("Headquarters")
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("headquarters");

                    b.Property<DateOnly?>("SourceUpdated")
                        .HasColumnType("date")
                        .HasColumnName("source_updated");

                    b.HasKey("UnitId")
                        .HasName("pk_administrative_boundary");

                    b.HasIndex("Boundary")
                        .HasDatabaseName("ix_bnd_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "gist");

                    b.HasIndex("BoundaryLod1")
                        .HasDatabaseName("ix_bnd_geom_lod1");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("BoundaryLod1"), "gist");

                    b.HasIndex("Centroid")
                        .HasDatabaseName("ix_bnd_centroid");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Centroid"), "gist");

                    b.ToTable("administrative_boundary", "adm");
                });

            modelBuilder.Entity("CivicFlow.Modules.AdministrativeUnits.Entities.AdministrativeUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("data_source");

                    b.Property<bool>("IsAuthoritative")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_authoritative");

                    b.Property<string>("LegalBasis")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("legal_basis");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name_normalized");

                    b.Property<string>("ParentCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("parent_code");

                    b.Property<string>("ShortName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("short_name");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unit_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_administrative_unit");

                    b.HasIndex("Code")
                        .HasDatabaseName("ix_adm_code");

                    b.HasIndex("Level")
                        .HasDatabaseName("ix_adm_level_valid")
                        .HasFilter("valid_to IS NULL");

                    b.HasIndex("NameNormalized")
                        .HasDatabaseName("ix_adm_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NameNormalized"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NameNormalized"), new[] { "gin_trgm_ops" });

                    b.HasIndex("ParentCode")
                        .HasDatabaseName("ix_adm_parent")
                        .HasFilter("valid_to IS NULL");

                    b.HasIndex("Code", "ValidFrom")
                        .IsUnique()
                        .HasDatabaseName("uq_adm_code_valid_from");

                    b.ToTable("administrative_unit", "adm", t =>
                        {
                            t.HasCheckConstraint("ck_adm_level", "level IN (1, 3)");

                            t.HasCheckConstraint("ck_adm_period", "valid_to IS NULL OR valid_to > valid_from");
                        });
                });

            modelBuilder.Entity("CivicFlow.Modules.AdministrativeUnits.Entities.DatasetVersion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_dataset_version");

                    b.ToTable("dataset_version", "adm", t =>
                        {
                            t.HasCheckConstraint("ck_singleton", "id = 1");
                        });
                });

            modelBuilder.Entity("CivicFlow.Modules.AdministrativeUnits.Entities.UnitMapping", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Confidence")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasDefaultValue(1.000m)
                        .HasColumnName("confidence");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<string>("LegalBasis")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("legal_basis");

                    b.Property<string>("MappingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mapping_type");

                    b.Property<string>("NewCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("new_code");

                    b.Property<short?>("NewLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("new_level");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("OldCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("old_code");

                    b.Property<string>("OldFullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("old_full_name");

                    b.Property<short>("OldLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("old_level");

                    b.Property<string>("OldNameNorm")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("old_name_norm");

                    b.HasKey("Id")
                        .HasName("pk_unit_mapping");

                    b.HasIndex("NewCode")
                        .HasDatabaseName("ix_map_new");

                    b.HasIndex("OldNameNorm")
                        .HasDatabaseName("ix_map_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("OldNameNorm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("OldNameNorm"), new[] { "gin_trgm_ops" });

                    b.HasIndex("OldCode", "OldLevel")
                        .HasDatabaseName("ix_map_old");

                    b.ToTable("unit_mapping", "adm");
                });

            modelBuilder.Entity("CivicFlow.Modules.AdministrativeUnits.Entities.AdministrativeBoundary", b =>
                {
                    b.HasOne("CivicFlow.Modules.AdministrativeUnits.Entities.AdministrativeUnit", "Unit")
                        .WithOne("Boundary")
                        .HasForeignKey("CivicFlow.Modules.AdministrativeUnits.Entities.AdministrativeBoundary", "UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_administrative_boundary_administrative_units_unit_id");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("CivicFlow.Modules.AdministrativeUnits.Entities.AdministrativeUnit", b =>
                {
                    b.Navigation("Boundary");
                });
#pragma warning restore 612, 618
        }
    }
}
